version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/open-wechat"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/open-wechat"
    schedule:
      interval: "daily"
