[package]
name = "open-wechat"
version = "0.1.0"
edition = "2021"
authors = ["HeadIron <i@liangzhicheng.cc>"]
description = "A rust sdk for wechat miniprogram open api"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
