[package]
name = "open-wechat"
version = "0.1.1"
edition = "2021"
authors = ["HeadIron <i@liangzhicheng.cc>"]
description = "A rust sdk for wechat miniprogram open api"
license = "MIT"
homepage = "https://github.com/headironc/open-wechat"
repository = "https://github.com/headironc/open-wechat"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.22", features = ["json"] }
async-trait = "0.1.74"
thiserror = "1.0.50"
tracing = "0.1.40"
serde = { version = "1.0.193", features = ["derive"] }
serde_repr = "0.1.17"
serde_json = "1.0.108"
